### ISSUE TITLE
Rename toJson to asJson

### ISSUE THREAD

**Issue by vkostyukov** [travisbrown/jfc#1]
@travisbrown what do you think about renaming `toJson` to `asJson`? I'm a huge fan of symmetric names for methods that do symmetirc things. Now you can go from `A` to `Json` with `toJson`, but in opposite way (`Json` to `A`) is `as[A]`.

If it sounds good to you I can put together a PR.

**Comment by propensive** [comment]
My general rule is that a method called `to` takes a type constructor, whereas a method called `as` takes a proper type.

**Comment by travisbrown** [comment]
I think that to me `to` means conversion, and specifically conversion that can fail, while `as` is more like safe casting or interpretation—but that's exactly the opposite of my current API, so I'm clearly not thinking too consistently about this stuff.

I say let's go with @propensive's rule and @vkostyukov's suggestion and use `as[A]` and `asJson`.
