### ISSUE TITLE
What about allocations?

### ISSUE THREAD

**Issue by vkostyukov** [travisbrown/jfc#2]
It would be absolutely terrifc to re-run JMH with `-prof gc` and add one more line for each performnace run: `gc.alloc.norm` (or something like this): bytes per iteration.

**Comment by travisbrown** [comment]
I've just posted the output [as a gist](https://gist.github.com/travisbrown/fe462ce02dcffb21536e)—let's keep this issue open until we've got those results integrated into the README in a way that isn't too noisy.

**Comment by vkostyukov** [comment]
Thanks! Resluts look very prommising! :+1: Nice work!
